### alle Schulen
GET http://localhost:8082/schule

### alle Grundschulen
GET http://localhost:8082/schule/bySchulform/Grundschule

### Schule mit einer Schul-ID
GET http://localhost:8082/schule/bySchulId/schule_000

### eine Schule mit Klasse und Fach hinzufügen
PUT http://localhost:8082/schule
Content-Type: application/json

{
  "schulname": "Meine Schule 5",
  "schulId": "schule_001",
  "schulform": "GRUNDSCHULE",
  "klassen": [
    {
      "bezeichnung": "1b",
      "klassenstufe": 1,
      "unterrichtList": [
        {
          "fach": {
            "bezeichnung": "Deutsch"
          },
          "anzahlProWoche": 6
        },
        {
          "fach": {
            "bezeichnung": "Mathe"
          },
          "anzahlProWoche": 5
        }
      ]
    },
    {
      "bezeichnung": "2a",
      "klassenstufe": 2,
      "unterrichtList": [
        {
          "fach": {
            "bezeichnung": "Deutsch"
          },
          "anzahlProWoche": 4
        }
      ]
    }
  ]
}

### Alle Fächer
GET http://localhost:8082/fach

### ein Fach hinzufügen
PUT http://localhost:8082/fach
Content-Type: application/json

{
  "bezeichnung": "Sport"
}