### alle Schulen
GET http://localhost:8082/schule

### alle Grundschulen
GET http://localhost:8082/schule/bySchulform/Grundschule

### Schule mit einer Schul-ID
GET http://localhost:8082/schule/bySchulId/schule_000

### eine Schule mit Klasse und Fach hinzufügen
PUT http://localhost:8082/schule
Content-Type: application/json

{
  "schulname": "Meine Schule 5",
  "schulId": "schule_000",
  "schulform": "GRUNDSCHULE",
  "klassen": [
    {
      "bezeichnung": "1b",
      "klassenstufe": 1
    },
    {
      "bezeichnung": "2a",
      "klassenstufe": 2
    }
  ]
}




### eine Schule löschen
DELETE http://localhost:8081/schule/schule_1234

### alle Klassen
GET http://localhost:8081/klasse